import os
from pathlib import Path

# List of unreferenced files to delete (from the attachment)
files_to_delete = [
    "includes/core-visuals/axis-range-logarithmic-scale.md",
    "includes/core-visuals/axis-range-maximum.md",
    "includes/core-visuals/axis-range-minimum.md",
    "includes/core-visuals/axis-title-style.md",
    "includes/core-visuals/axis-title-title-text.md",
    "includes/core-visuals/border-&-divider-line-style.md",
    "includes/core-visuals/callout-values-label-align-baselines.md",
    "includes/core-visuals/callout-values-label-heading.md",
    "includes/core-visuals/callout-values-label-match-value-alignment.md",
    "includes/core-visuals/callout-values-label-position.md",
    "includes/core-visuals/callout-values-label-space-between-label-and-value.md",
    "includes/core-visuals/callout-values-label-text.md",
    "includes/core-visuals/callout-values-layout-callout-size.md",
    "includes/core-visuals/callout-values-values-horizontal-alignment.md",
    "includes/core-visuals/callout-values-values-text-wrap.md",
    "includes/core-visuals/cards-accent-bar-position.md",
    "includes/core-visuals/cards-alignment-vertical-alignment.md",
    "includes/core-visuals/cards-glow-offset.md",
    "includes/core-visuals/cards-glow-size.md",
    "includes/core-visuals/cards-shadow-glow-angle.md",
    "includes/core-visuals/cards-shadow-glow-blur.md",
    "includes/core-visuals/cards-shadow-glow-distance.md",
    "includes/core-visuals/cards-shadow-size.md",
    "includes/core-visuals/columns-apply-settings-to-categories.md",
    "includes/core-visuals/columns-apply-settings-to.md",
    "includes/core-visuals/columns-border-hide-inner-borders.md",
    "includes/core-visuals/columns-border-match-column-color.md",
    "includes/core-visuals/columns-color-apply-settings-to-color.md",
    "includes/core-visuals/columns-layout-flip-overlap.md",
    "includes/core-visuals/columns-layout-overlap.md",
    "includes/core-visuals/columns-layout-reverse-order.md",
    "includes/core-visuals/columns-layout-series-explosion.md",
    "includes/core-visuals/columns-layout-sort-by-value.md",
    "includes/core-visuals/columns-layout-space-between-categories.md",
    "includes/core-visuals/columns-layout-space-between-series.md",
    "includes/core-visuals/customize-lines-toggle.md",
    "includes/core-visuals/data-labels-detail-field.md",
    "includes/core-visuals/data-labels-options-optimize-label-display.md",
    "includes/core-visuals/data-labels-options-orientation.md",
    "includes/core-visuals/data-labels-options-overflow-text.md",
    "includes/core-visuals/data-labels-options-position.md",
    "includes/core-visuals/data-labels-title-content.md",
    "includes/core-visuals/data-labels-title-data.md",
    "includes/core-visuals/data-labels-value-field.md",
    "includes/core-visuals/error-bars-apply-settings-to.md",
    "includes/core-visuals/error-bars-bar-bar-color.md",
    "includes/core-visuals/error-bars-bar-border-color.md",
    "includes/core-visuals/error-bars-bar-border-size.md",
    "includes/core-visuals/error-bars-bar-marker-shape.md",
    "includes/core-visuals/error-bars-bar-marker-size.md",
    "includes/core-visuals/error-bars-error-labels-label-format.md",
    "includes/core-visuals/error-bars-error-labels-show-background.md",
    "includes/core-visuals/error-bars-options-enabled-toggle.md",
    "includes/core-visuals/error-bars-options-lower-bound.md",
    "includes/core-visuals/error-bars-options-make-symmetrical.md",
    "includes/core-visuals/error-bars-options-relationship-to-measure.md",
    "includes/core-visuals/error-bars-options-type.md",
    "includes/core-visuals/error-bars-options-upper-bound.md",
    "includes/core-visuals/global-apply-settings-to-series-menu.md",
    "includes/core-visuals/global-apply-settings-to-series.md",
    "includes/core-visuals/global-background-image-browse.md",
    "includes/core-visuals/global-bottom-left-corner.md",
    "includes/core-visuals/global-bottom-right-corner.md",
    "includes/core-visuals/global-color-palette-fx.md",
    "includes/core-visuals/global-continuous-axis-display-units.md",
    "includes/core-visuals/global-customize-corners.md",
    "includes/core-visuals/global-dash-array.md",
    "includes/core-visuals/global-dash-cap.md",
    "includes/core-visuals/global-display-units.md",
    "includes/core-visuals/global-format-code-fx.md",
    "includes/core-visuals/global-image-fit.md",
    "includes/core-visuals/global-line-style.md",
    "includes/core-visuals/global-match-series-color.md",
    "includes/core-visuals/global-padding-padding.md",
    "includes/core-visuals/global-padding-size.md",
    "includes/core-visuals/global-padding.md",
    "includes/core-visuals/global-rounded-corners.md",
    "includes/core-visuals/global-scale-by-width.md",
    "includes/core-visuals/global-shadow-and-glow-position.md",
    "includes/core-visuals/global-shadow-offset.md",
    "includes/core-visuals/global-show-blank-as.md",
    "includes/core-visuals/global-top-left-corner.md",
    "includes/core-visuals/global-top-right-corner.md",
    "includes/core-visuals/global-value-decimal-places-fx.md",
    "includes/core-visuals/global-vertical-alignment.md",
    "includes/core-visuals/global-width-0-12.md",
    "includes/core-visuals/global-width-0-4.md",
    "includes/core-visuals/image-transparency.md",
    "includes/core-visuals/images-image-alt-text.md",
    "includes/core-visuals/images-image-browse.md",
    "includes/core-visuals/images-image-fix-size.md",
    "includes/core-visuals/images-image-image-area-size.md",
    "includes/core-visuals/images-image-image-type.md",
    "includes/core-visuals/images-image-image-url.md",
    "includes/core-visuals/images-image-position.md",
    "includes/core-visuals/images-image-size.md",
    "includes/core-visuals/images-image-space-between-image-and-callout.md",
    "includes/core-visuals/layout-layout-arrangement.md",
    "includes/core-visuals/layout-layout-columns-shown.md",
    "includes/core-visuals/layout-layout-customize-spacing.md",
    "includes/core-visuals/layout-layout-max-cards-shown.md",
    "includes/core-visuals/layout-layout-max-rows-shown.md",
    "includes/core-visuals/layout-layout-space-between-cards.md",
    "includes/core-visuals/layout-layout-space-between-columns.md",
    "includes/core-visuals/layout-layout-space-between-rows.md",
    "includes/core-visuals/layout-layout-style.md",
    "includes/core-visuals/layout-overflow-overflow-direction.md",
    "includes/core-visuals/layout-overflow-overflow-style.md",
    "includes/core-visuals/legend-options-position.md",
    "includes/core-visuals/legend-title-title-text.md",
    "includes/core-visuals/plot-area-background-browse.md",
    "includes/core-visuals/prerequisites-desktop-preview-features-new-card-visual.md",
    "includes/core-visuals/reference-labels-add-label.md",
    "includes/core-visuals/reference-labels-apply-settings-to-select-label.md",
    "includes/core-visuals/reference-labels-apply-settings-to-select-series.md",
    "includes/core-visuals/reference-labels-detail-data.md",
    "includes/core-visuals/reference-labels-detail-font-color.md",
    "includes/core-visuals/reference-labels-divider-ignore-padding.md",
    "includes/core-visuals/reference-labels-layout-arrangement.md",
    "includes/core-visuals/reference-labels-layout-horizontal-alignment.md",
    "includes/core-visuals/reference-labels-layout-style.md",
    "includes/core-visuals/reference-labels-layout-value-area.md",
    "includes/core-visuals/reference-labels-layout-vertical-alignment.md",
    "includes/core-visuals/reference-labels-options-position.md",
    "includes/core-visuals/reference-labels-spacing-customize-outer-padding.md",
    "includes/core-visuals/reference-labels-spacing-outer-padding.md",
    "includes/core-visuals/reference-labels-spacing-padding-after.md",
    "includes/core-visuals/reference-labels-spacing-padding-before.md",
    "includes/core-visuals/reference-labels-spacing-space-between-labels.md",
    "includes/core-visuals/reference-labels-title-text.md",
    "includes/core-visuals/reference-line-add-line.md",
    "includes/core-visuals/reference-line-apply-settings-to-type.md",
    "includes/core-visuals/reference-line-apply-settings-to.md",
    "includes/core-visuals/reference-line-data-label-horizontal-position.md",
    "includes/core-visuals/reference-line-data-label-style.md",
    "includes/core-visuals/reference-line-data-label-vertical-position.md",
    "includes/core-visuals/reference-line-line-percentile.md",
    "includes/core-visuals/reference-line-line-position.md",
    "includes/core-visuals/reference-line-line-value.md",
    "includes/core-visuals/reference-line-series-series.md",
    "includes/core-visuals/reference-line-shade-area-position.md",
    "includes/core-visuals/ribbons-border-match-ribbon-color.md",
    "includes/core-visuals/ribbons-layout-space-between-ribbons-and-columns.md",
    "includes/core-visuals/shape-bottom-left-corner.md",
    "includes/core-visuals/shape-bottom-right-corner.md",
    "includes/core-visuals/shape-customize-style.md",
    "includes/core-visuals/shape-rounded-corners.md",
    "includes/core-visuals/shape-shape.md",
    "includes/core-visuals/shape-size-of-bottom-snips.md",
    "includes/core-visuals/shape-size-of-top-snips.md",
    "includes/core-visuals/shape-top-left-corner.md",
    "includes/core-visuals/shape-top-right-corner.md",
    "includes/core-visuals/small-multiples-background-color-palette-fx.md",
    "includes/core-visuals/small-multiples-border-gridlines.md",
    "includes/core-visuals/small-multiples-layout-all-padding.md",
    "includes/core-visuals/small-multiples-layout-columns.md",
    "includes/core-visuals/small-multiples-layout-customize-padding.md",
    "includes/core-visuals/small-multiples-layout-rows.md",
    "includes/core-visuals/total-labels-values-display-units.md",
    "includes/core-visuals/total-labels-values-split.md",
    "includes/core-visuals/xaxis-layout-minimum-category-width.md",
    "includes/core-visuals/xaxis-range-invert-range.md",
    "includes/core-visuals/xaxis-type-type.md",
    "includes/core-visuals/xaxis-values-concatenate-labels.md",
    "includes/core-visuals/xaxis-values-maximum-height.md",
    "includes/core-visuals/xaxis-values-value-decimal-places.md",
    "includes/core-visuals/yaxis-values-switch-axis-position.md"
]

base_dir = Path(r'c:\repos\powerbi-docs-pr\powerbi-docs')

deleted_count = 0
failed_count = 0
failed_files = []

for file_path in files_to_delete:
    full_path = base_dir / file_path
    try:
        if full_path.exists():
            full_path.unlink()
            deleted_count += 1
            print(f"Deleted: {file_path}")
        else:
            print(f"Not found: {file_path}")
            failed_count += 1
            failed_files.append(file_path)
    except Exception as e:
        print(f"Error deleting {file_path}: {e}")
        failed_count += 1
        failed_files.append(file_path)

print(f"\n=== Summary ===")
print(f"Successfully deleted: {deleted_count} files")
print(f"Failed/Not found: {failed_count} files")

if failed_files:
    print(f"\nFailed files:")
    for f in failed_files:
        print(f"  - {f}")
