---
title: Add copilot summaries to email subscriptions
description: Using Copilot, you can quickly create a Power BI report.
author: nirusrin
ms.author: nisrinivasan
ms.reviewer: maggieMSFT
ms.service: powerbi
ms.subservice: pbi-reports-dashboards
ms.topic: how-to
ms.date: 10/18/2024
LocalizationGroup: Create report subscriptions
no-loc: [Copilot]
ms.collection: ce-skilling-ai-copilot
#customer intent: As a report subscription creator, I want sopilot report summaries to be delivered in my subscription email.
---

# Create reports in the Power BI service with Copilot

[!INCLUDE [applies-no-desktop-yes-service](../includes/applies-no-desktop-yes-service.md)]

You can include a Copilot generated summary for your Power BI report page or full report attachment in your email subscription to get insights. All the recipients of the email subscription will receive the copilot summary in the email. This feature is currently supported for Standard Subscriptions  
The copilot summary is also delivered to email even for reports that are delivered to OneDrive or SharePoint.

# Licensing Requirements

- Ensure you have [reviewed](../copilot-enable-power-bi) what's required to get copilot to work in Power BI
- (Add link to subscriptions licensing requirements) 
- Your administrator needs to enable the tenant switch before you start using Copilot. See the article Copilot tenant settings for details.
- Your F64 or P1 capacity needs to be in one of the regions listed in this article, Fabric region availability. If it isn't, you can't use Copilot.

# How to setup Copilot in email subscriptions

1. Select **Subscribe to report** , then select **Create a subscription**

:::image type="content" source="media/copilot-summaries-in-subscriptions/power-bi-subscibe-to-report.png" alt-text="Screenshot showing how to subscribe to a report." lightbox="media/copilot-summaries-in-subscriptions/power-bi-subscibe-to-report.png":::


2. Select **Standard Subscription**. You can choose to modify the **Subscription name**, **Recipients** who you want to receive the copilot summary in email.

:::image type="content" source="media/copilot-summaries-in-subscriptions/power-bi-standard-subscription.png" alt-text="Screenshot showing creating a std. subscription." lightbox="media/copilot-summaries-in-subscriptions/power-bi-standard-subscription.png":::

3. You can choose to receive a summary of a single report page or the full report by choosing **Attach full report**. This option will also attach the report to the email.

:::image type="content" source="media/copilot-summaries-in-subscriptions/power-bi-attach-full-report.png" alt-text="Screenshot showing FRA subscription." lightbox="media/copilot-summaries-in-subscriptions/power-bi-attach-full-report.png":::

You can also choose to deliver the full report to a OneDrive or SharePoint location. If you choose to do this, the copilot summary will still be delivered to the recipient email.

:::image type="content" source="media/copilot-summaries-in-subscriptions/power-bi-send-to.png" alt-text="Screenshot showing ODSP subscription." lightbox="media/copilot-summaries-in-subscriptions/power-bi-send-to.png":::

4. Schedule the delivery (add link) of your report. 

5. The **Summary by copilot (preview)** will be included in the email. 

:::image type="content" source="media/copilot-summaries-in-subscriptions/power-bi-subscribe-copilot-summaries-email.png" alt-text="Screenshot showing opt-in for summary for the subscription." lightbox="media/copilot-summaries-in-subscriptions/power-bi-subscribe-copilot-summaries-email.png":::

6. You can choose to **Preview summary** 

:::image type="content" source="media/copilot-summaries-in-subscriptions/power-bi-subscribe-preview-copilot-summary.png" alt-text="Screenshot showing the preview for summary for the subscription." lightbox="media/copilot-summaries-in-subscriptions/power-bi-subscribe-preview-copilot-summary.png":::

7. You can choose to opt-out of including Copilot summaries in subscriptions by turning off the toggle.

:::image type="content" source="media/copilot-summaries-in-subscriptions/power-bi-subscribe-copilot-summaries-off.png" alt-text="Screenshot showing the opt-out for the summary in the subscription." lightbox="media/copilot-summaries-in-subscriptions/power-bi-subscribe-copilot-summaries-off.png":::

8. You can choose to include an email subject, message , an image of a report page, a link to the report in Power BI and permission to view the report in Power BI.
If you include a message in the email, the message will appear above the Summary generated by copilot.

9. **Save** the subscription.

10. Once you have saved the subscription, you can test the subscription by selecting the **Send now** button.

:::image type="content" source="media/copilot-summaries-in-subscriptions/power-bi-subscribe-copilot-summaries-send-now.png" alt-text="Screenshot showing the send now option." lightbox="media/power-bi-subscribe-copilot-summaries-send-now.png":::

# Limitations and Considerations
- Copilot summaries for email subscriptions are not supported for pagintaed reports, scrorecards and dashboards.
- The Copilot summary is run on behalf of the subscription owner, much like email subscriptions.
- User-defined prompts are not supported. 
