start desktop-automatic-page-refresh.md
start desktop-performance-analyzer.md
start desktop-visual-elements-for-reports.md 
start desktop-tooltips.md
start desktop-export-to-pdf.md 
start desktop-insights.md
start desktop-insights-find-where-different.md
start desktop-buttons.md
start desktop-drill-through-buttons.md
start desktop-drillthrough.md
start desktop-cross-report-drill-through.md
start desktop-bookmarks.md
start desktop-report-themes.md
start power-bi-report-filter.md
start power-bi-report-add-filter.md
start desktop-grouping-and-binning.md
start desktop-gridlines-snap-to-grid.md
start power-bi-report-display-settings.md
start desktop-add-column-from-example.md
start desktop-add-custom-column.md
start desktop-inline-hierarchy-labels.md
start ../visuals/power-bi-visualization-slicers.md
start desktop-slicer-numeric-range.md
start ../visuals/desktop-slicer-filter-date-range.md
start slicer-filter-relative-time.md
start power-bi-slicer-filter-responsive.md
start power-bi-slicer-hierarchy-multiple-fields.md
start desktop-rls.md
start desktop-custom-tooltips.md
start power-bi-reports-add-text-and-shapes.md
start service-add-hyperlink-to-text-box.md
start power-bi-hyperlinks-in-tables.md
start power-bi-images-tables.md
start desktop-custom-format-strings.md
start desktop-conditional-table-formatting.md
start desktop-conditional-format-visual-titles.md
start desktop-sort-by-column.md
start desktop-create-phone-report.md
start desktop-see-data-see-records.md
start desktop-tips-and-tricks-for-creating-reports.md
start desktop-grouping-visuals.md
start desktop-templates.md
start service-report-create-new.md
start service-report-save.md
start service-interact-with-a-report-in-editing-view.md
start ../collaborate-share/service-analyze-in-excel.md
start service-aggregates.md
start service-create-qr-code-for-report.md
start power-bi-personalize-visuals.md
start service-export-to-pbix.md
start desktop-upload-desktop-files.md
start ../visuals/power-bi-report-add-visualizations-i.md
start ../visuals/power-bi-report-add-visualizations-ii.md
start ../visuals/power-bi-report-visualizations.md
start ../visuals/power-bi-report-change-visualization-type.md
start ../visuals/power-bi-visualization-customize-title-background-and-legend.md
start desktop-show-items-no-data.md
start ../visuals/power-bi-data-points.md
start ../visuals/service-reports-show-data.md
start ../visuals/service-getting-started-with-color-formatting-and-axis-properties.md
start ../visuals/service-tips-and-tricks-for-color-formatting.md
start ../visuals/power-bi-visualization-copy-paste.md
start ../visuals/power-bi-visualization-export-data.md
start ../visuals/power-bi-visualization-move-and-resize.md
start service-reports-visual-interactions.md
start ../visuals/power-bi-map-tips-and-tricks.md
start ../visuals/power-bi-visualization-customize-x-axis-and-y-axis.md
start ../visuals/power-bi-visualizations-arcgis.md
start ../visuals/power-bi-visualization-arcgis.md
start ../visuals/power-bi-visualization-basic-area-chart.md
start ../visuals/power-bi-visualization-card.md
start ../visuals/power-bi-visualization-combo-chart.md
start ../visuals/power-bi-visualization-decomposition-tree.md
start ../visuals/power-bi-visualization-doughnut-charts.md
start ../visuals/power-bi-visualization-filled-maps-choropleths.md
start ../visuals/power-bi-visualization-funnel-charts.md
start ../visuals/power-bi-visualization-influencers.md
start ../visuals/power-bi-visualization-kpi.md
start ../visuals/desktop-matrix-visual.md
start ../visuals/power-bi-visualization-powerapp.md
start ../visuals/service-r-visuals.md
start desktop-r-visuals.md
start desktop-r-powered-custom-visuals.md
start ../visuals/power-bi-visualization-radial-gauge-charts.md
start ../visuals/desktop-ribbon-charts.md
start ../visuals/power-bi-visualization-scatter.md
start ../visuals/desktop-high-density-scatter-charts.md
start ../visuals/desktop-shape-map.md
start ../visuals/power-bi-visualization-tables.md
start ../visuals/power-bi-visualization-treemaps.md
start ../visuals/power-bi-visualization-waterfall-charts.md
start ../visuals/power-bi-visualization-q-and-a.md
start ../natural-language/q-and-a-tooling-teach-q-and-a.md
start ../natural-language/q-and-a-best-practices.md
start power-bi-tutorial-q-and-a.md
start power-bi-visualization-introduction-to-q-and-a.md
start service-prepare-data-for-q-and-a.md
start service-q-and-a-create-featured-questions.md
start service-q-and-a-direct-query.md
start service-insights.md
start service-insights-optimize.md
start desktop-accessibility-creating-reports.md
start desktop-accessibility-creating-tools.md 
start desktop-accessibility-consuming-tools.md 
start desktop-accessibility-keyboard-shortcuts.md
start ../paginated-reports/paginated-reports-enter-data.md
start ../paginated-reports/paginated-reports-embedded-data-source.md
start ../paginated-reports/paginated-reports-create-embedded-dataset.md
start ../paginated-reports/report-builder-shared-datasets.md
start ../paginated-reports/paginated-reports-parameters.md
start ../paginated-reports/page-view.md
start ../paginated-reports/subreports.md
start ../paginated-reports/subreports-troubleshoot.md
start ../paginated-reports/report-builder-url-pass-parameters.md
start ../paginated-reports/paginated-reports-save-to-power-bi-service.md
start service-dashboards.md
start service-dashboard-tiles.md
start service-dashboard-create.md
start service-dashboard-copy.md
start service-dashboard-pin-tile-from-report.md
start service-pin-tile-to-another-dashboard.md
start service-dashboard-pin-tile-from-excel.md
start service-dashboard-pin-tile-from-q-and-a.md
start service-dashboard-pin-live-tile-from-report.md
start service-set-data-alerts.md
start service-dashboard-add-widget.md
start service-dashboard-edit-tile.md
start service-dashboards-design-tips.md
start service-create-dashboard-mobile-phone-view.md
start service-create-qr-code-for-tile.md
start service-data-classification.md
start service-dashboard-themes.md
start deployment-pipelines-get-started.md
start deployment-pipelines-troubleshooting.md
start service-rename.md
start service-item-contact.md
start service-delete.md
