
sed -i 's|https://support.powerbi.com/knowledgebase/articles/667840|powerbi-admin-power-bi-security.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/436810|powerbi-admin-get-help-and-support-with-power-bi.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/670012|powerbi-admin-administering-power-bi-in-your-organization.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/657085|powerbi-admin-manage-your-data-storage-in-power-bi.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/685632|powerbi-admin-purchasing-power-bi-pro.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/492388|powerbi-admin-migrating-to-the-new-power-bi-experience.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/677563|powerbi-admin-power-bi-archived-workspace.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/546004|powerbi-admin-analysis-services-connector-indepth.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/497354|powerbi-admin-data-management-gateway-in-office-365.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/471189|powerbi-admin-closing-your-account.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/587907|powerbi-service-create-a-big-number-tile-from-a-power-bi-report.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/431008|powerbi-service-share-unshare-dashboard.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/475163|powerbi-service-create-a-dashboard.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/425669|powerbi-service-dashboard-tiles.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/430323|powerbi-service-pin-a-tile-to-a-dashboard-from-a-report.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/433616|powerbi-service-tips-for-designing-a-great-dashboard.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/424874|powerbi-service-pin-a-tile-to-a-dashboard-from-the-question-box.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/424878|powerbi-service-edit-a-tile-in-a-dashboard.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/582552|powerbi-service-add-an-image-to-a-dashboard.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/436733|powerbi-service-create-a-big-number-tile-for-a-dashboard.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/475172|powerbi-service-rename-a-dashboard.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/475173|powerbi-service-delete-or-remove-a-dashboard.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/665494|powerbi-service-the-report-editor-take-a-tour.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/663517|powerbi-service-converting-your-reports-to-the-new-report-editor.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/464704|powerbi-service-add-a-filter-to-a-report.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/475616|powerbi-service-create-a-new-report.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/467092|powerbi-service-about-filters-and-highlighting-in-reports.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/445094|powerbi-service-interact-with-a-report-in-reading-view.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/546859|powerbi-service-how-to-use-a-report-filter.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/443094|powerbi-service-interact-with-a-report-in-editing-view.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/439920|powerbi-service-open-a-report-in-reading-view.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/475147|powerbi-service-aggregates-in-reports.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/439921|powerbi-service-go-from-reading-view-to-editing-view.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/474804|powerbi-service-add-a-page-to-a-report.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/444112|powerbi-service-save-a-report.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/474347|powerbi-service-rename-a-report.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/475186|powerbi-service-reorder-pages-in-a-report.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/474805|powerbi-service-delete-a-page-from-a-report.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/474346|powerbi-service-delete-a-report.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/636088|powerbi-azure-sql-data-warehouse-with-direct-connect.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/654094|powerbi-spark-on-hdinsight-with-direct-connect.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/471577|powerbi-analysis-services-connector.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/471633|powerbi-sql-server-analysis-services-tabular-data.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/581421|powerbi-azure-sql-database-with-direct-connect.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/568614|powerbi-azure-and-power-bi.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/640168|powerbi-bring-in-whole-excel-files.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/655108|powerbi-replace-an-excel-power-bi-desktop-or-csv-file.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/723615|powerbi-reduce-the-size-of-an-excel-workbook.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/424871|powerbi-service-excel-data.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/597003|powerbi-service-get-data-from-files.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/471009|powerbi-service-refresh-excel-data-stored-in-onedrive.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/651040|powerbi-service-organizational-content-packs-introduction.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/651337|powerbi-service-organizational-content-pack-tutorial-create-and-publish.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/651631|powerbi-service-organizational-content-packs-manage-update-delete.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/651715|powerbi-service-organizational-content-pack-find-and-open.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/651727|powerbi-service-organizational-content-packs-use-and-work-with.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/663661|powerbi-service-organizational-content-pack-delete.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/649846|powerbi-personal-gateway.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/474669|powerbi-refresh-data.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/475435|powerbi-service-important-considerations-for-connecting-to-data-in-power-bi.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/475159|powerbi-service-explore-a-dataset.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/475378|powerbi-service-delete-a-dataset-from.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/475376|powerbi-service-rename-a-dataset-in-power-bi.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/675508|powerbi-frequently-asked-questions.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/685479|powerbi-power-bi-pro-content-what-is-it.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/664495|powerbi-free-trial-for-power-bi-pro.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/652525|powerbi-power-bi-apps-for-mobile-devices.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/430814|powerbi-service-get-started.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/471112|powerbi-sample-datasets.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/487029|powerbi-service-basic-concepts.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/434354|powerbi-service-get-data.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/424868|powerbi-service-dashboards.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/425684|powerbi-service-reports.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/475702|powerbi-videos.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/474566|powerbi-service-q-and-a.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/443109|powerbi-service-browser-support.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/559626|powerbi-supported-languages.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/587886|powerbi-webinars.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/473409|powerbi-service-whats-new.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/654247|powerbi-service-groups.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/654250|powerbi-service-create-a-group-in-power-bi.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/664471|powerbi-service-manage-your-group-in-power-bi-and-office-365.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/664462|powerbi-service-connect-to-files-on-your-groups-onedrive-for-business.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/665374|powerbi-service-collaborate-with-your-power-bi-group.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/628531|powerbi-service-mobile-known-issues-in-the-ipad-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/721749|powerbi-service-mobile-groups-in-the-ipad-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/527003|powerbi-mobile-ipad-iphone-apps.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/467172|powerbi-mobile-iphone-app-get-started.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/467176|powerbi-mobile-dashboards-on-the-ipad-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/467180|powerbi-mobile-reports-on-the-ipad-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/467181|powerbi-mobile-share-dashboards-from-the-ipad-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/467178|powerbi-mobile-tiles-in-the-ipad-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/527030|powerbi-mobile-annotate-and-share-a-snapshot-from-the-ipad-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/467179|powerbi-mobile-favorites-on-the-ipad-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/629869|powerbi-mobile-known-issues-with-the-iphone-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/721782|powerbi-mobile-groups-in-the-iphone-app-groups.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/527036|powerbi-mobile-ipad-app-get-started.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/527063|powerbi-mobile-set-data-alerts-in-the-iphone-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/527051|powerbi-mobile-dashboards-in-the-iphone-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/527054|powerbi-mobile-tiles-in-the-iphone-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/527075|powerbi-mobile-share-a-dashboard-from-the-iphone-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/527099|powerbi-mobile-annotate-and-share-a-tile-from-the-iphone-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/527060|powerbi-mobile-favorites-in-the-iphone-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/725667|powerbi-mobile-whats-new-in-the-mobile-apps.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/608316|powerbi-mobile-dashboards-in-the-android-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/577785|powerbi-mobile-get-the-power-bi-for-android-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/608319|powerbi-mobile-tiles-in-the-android-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/608337|powerbi-mobile-share-a-dashboard-from-the-android-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/608328|powerbi-mobile-favorites-in-the-android-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/608340|powerbi-mobile-annotate-and-share-a-tile-from-the-android-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/718203|powerbi-mobile-groups-in-the-android-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/577773|powerbi-mobile-android-app-get-started.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/683479|powerbi-mobile-groups-in-the-windows-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/510917|powerbi-service-windows-app-get-started.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/510955|powerbi-mobile-share-dashboards-from-the-windows-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/536383|powerbi-mobile-get-the-windows-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/535432|powerbi-mobile-annotate-and-share-a-snapshot-from-the-windows-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/510951|powerbi-mobile-dashboards-in-the-windows-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/510953|powerbi-mobile-reports-in-the-windows-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/536281|powerbi-mobile-refresh-the-windows-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/510952|powerbi-mobile-tiles-in-the-windows-app.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/703422|powerbi-desktop-import-excel-workbooks.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/665278|powerbi-desktop-analysis-services-tabular-data.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/495096|powerbi-desktop-project-online-connect-to-data.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/663229|powerbi-desktop-relationship-view.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/663202|powerbi-desktop-data-view.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/729417|powerbi-desktop-pyramid-analytics.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/567183|powerbi-desktop-help.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/471597|powerbi-desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/471643|powerbi-desktop-data-sources.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/461312|powerbi-desktop-tutorial-facebook-analytics.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/461315|powerbi-desktop-tutorial-importing-and-analyzing-data-from-a-web-page.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/471664|powerbi-desktop-getting-started.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/489224|powerbi-desktop-latest-update.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/461292|powerbi-desktop-videos.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/464157|powerbi-desktop-tips-and-tricks-for-creating-reports.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/471648|powerbi-desktop-common-query-tasks.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/554619|powerbi-desktop-quickstart-learn-dax-basics.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/556656|powerbi-desktop-tutorial-create-measures.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/471644|powerbi-desktop-shape-and-combine-data.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/464158|powerbi-desktop-get-the-desktop.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/554577|powerbi-desktop-measures.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/461278|powerbi-desktop-upload-desktop-files.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/471635|powerbi-desktop-connect-to-data.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/590598|powerbi-desktop-calculated-columns.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/464155|powerbi-desktop-create-and-manage-relationships.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/471646|powerbi-desktop-query-overview.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/461283|powerbi-desktop-report-view.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/590610|powerbi-desktop-tutorial-create-calculated-columns.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/592116|powerbi-desktop-sort-by-column.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/558030|powerbi-desktop-data-types.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/594282|powerbi-desktop-data-categorization.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/591699|powerbi-service-google-analytics-connector.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/571845|powerbi-service-facebook-connector.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/607113|powerbi-service-tutorial-introduction-to-q-and-a.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/474690|powerbi-service-make-your-data-work-well-with-q-and-a.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/475138|powerbi-service-ask-the-right-questions-of-salesforce-data.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/510274|powerbi-sample-it-spend-analysis-sample-for-power-bi-take-a-tour.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/640117|powerbi-sample-connect-to-the-retail-analysis-sample-content-pack.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/510270|powerbi-sample-supplier-quality-analysis-sample-for-power-bi-take-a-tour.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/474807|powerbi-sample-retail-analysis-take-a-tour.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/497124|powerbi-sample-download-the-financial-sample-workbook.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/514904|powerbi-sample-downloads.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/462791|powerbi-content-pack-microsoft-dynamics-crm.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/511323|powerbi-content-pack-google-analytics.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/543394|powerbi-content-pack-visual-studio-online.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/424863|powerbi-content-pack-salesforce.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/596925|powerbi-content-pack-quickbooks-online.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/462794|powerbi-content-pack-github.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/654097|powerbi-content-pack-acumatica.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/462793|powerbi-content-pack-microsoft-dynamics-marketing.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/581499|powerbi-azure-sql-database-auditing-connector.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/462798|powerbi-content-pack-zendesk.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/462795|powerbi-content-pack-marketo.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/691725|powerbi-content-pack-mandrill.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/716718|powerbi-content-pack-adobe-analytics.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/618267|powerbi-content-pack-mailchimp.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/671314|powerbi-content-pack-sql-sentry.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/683708|powerbi-content-pack-circuit-id.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/613512|powerbi-content-pack-appfigures.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/703416|powerbi-content-pack-azure-mobile.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/462796|powerbi-content-pack-sendgrid.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/643387|powerbi-content-pack-uservoice.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/624282|powerbi-content-pack-sweetiq.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/591810|powerbi-content-pack-twilio.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/734013|powerbi-content-pack-content-pack.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/728691|powerbi-content-pack-tygraph.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/724662|powerbi-content-pack-webtrends.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/594453|powerbi-service-self-service-signup-for-power-bi.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/685803|powerbi-service-tips-and-tricks-for-power-bi-map-visualizations.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/594480|powerbi-admin-signing-up-for-power-bi-with-a-new-office-365-trial.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/685800|powerbi-service-reference-lines-in-your-report.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/685809|powerbi-service-histograms.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/722121|powerbi-developer-getting-started-with-developer-tools-preview.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/666367|powerbi-admin-troubleshooting-power-bi-personal-gateway.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/668836|powerbi-admin-service-health-status.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/711453|powerbi-admin-alternate-email-address-for-power-bi.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/600825|powerbi-admin-capturing-additional-diagnostic-information-for-power-bi.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/501937|powerbi-admin-troubleshoot-excel-workbook-data.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/505324|powerbi-admin-troubleshoot-analysis-service-connector.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/527228|powerbi-admin-troubleshooting-scheduled-refresh-azure-sql-databases.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/499083|powerbi-admin-how-to-use-the-same-account-as-azure.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/497728|powerbi-admin-forgot-your-password.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/666355|powerbi-service-tips-and-tricks-for-color-formatting.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/637429|powerbi-service-tutorial-customize-x-axis-and-y-axis-properties.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/653140|powerbi-service-tutorial-waterfall-charts.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/666325|powerbi-service-getting-started-with-color-formatting-and-axis-properties.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/637423|powerbi-service-tutorial-customize-visualization-title-background-and-legend.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/633580|powerbi-service-hyperlinks-in-tables.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/653149|powerbi-service-tutorial-basic-area-chart.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/653143|powerbi-service-tutorial-doughnut-charts.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/729906|powerbi-service-add-a-hyperlink-to-a-text-box.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/729903|powerbi-service-text-boxes-in-reports.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/469552|powerbi-service-visualization-types-for-reports-and-q-and-a.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/467072|powerbi-service-drill-down-in-a-visualization.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/434821|powerbi-service-visualizations-for-reports.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/556194|powerbi-service-tutorial-filled-maps-choropleths.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/436737|powerbi-service-tutorial-combo-chart-merge-visualizations.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/471200|powerbi-service-change-the-aggregation-in-a-chart.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/441777|powerbi-service-add-visualizations-to-a-report-i.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/556188|powerbi-service-tutorial-radial-gauge-charts.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/441746|powerbi-service-change-how-a-chart-is-sorted.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/467184|powerbi-service-add-visualizations-to-a-report-ii.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/556197|powerbi-service-tutorial-funnel-charts.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/556200|powerbi-service-tutorial-treemaps.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/444663|powerbi-service-change-the-type-of-visualization-in-a-report.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/436736|powerbi-service-copy-and-paste-a-visualization.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/465130|powerbi-service-move-and-resize-a-visualization.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/465144|powerbi-service-delete-a-visualization.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/742155|powerbi-service-change-report-display-settings.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/741510|powerbi-desktop-calculated-tables.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/510275|powerbi-sample-procurement-analysis-take-a-tour.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/737868|powerbi-content-pack-stripe.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/732231|powerbi-issue-what-if-my-data-isnt-up-to-date.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/747363|powerbi-service-tutorial-change-report-display-settings.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/742209|powerbi-refresh-troubleshooting-refresh-scenarios.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/743532|powerbi-service-how-to-use-q-and-a.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/510271|powerbi-sample-human-resources-take-a-tour.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/510268|powerbi-sample-sales-and-marketing-take-a-tour.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/742695|powerbi-content-pack-azure-audit-logs.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/742047|powerbi-admin-troubleshoot-unsupported-data-source-for-refresh.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/732219|powerbi-issue-i-need-help-signing-up-for-power-bi.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/743853|powerbi-admin-office-365-dedicated-known-issues.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/510270|powerbi-sample-supplier-quality-analysis-take-a-tour.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/735087|powerbi-pin-a-tile-from-one-dashboard-to-another.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/742023|powerbi-refresh-tools-for-troubleshooting-issues.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/736368|powerbi-service-how-should-I-share-my-dashboard.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/510269|powerbi-sample-customer-profitability-take-a-tour.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/510273|powerbi-sample-opportunity-analysis-take-a-tour.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/640117|powerbi-sample-tutorial-connect-to-the-samples.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/746439|powerbi-content-pack-microsoft-dynamics-nav.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/732222|powerbi-issue-i-get-an-error-refreshing-data-with-the-power-bi-personal-gateway.md|g' *.md
sed -i 's|https://support.powerbi.com/knowledgebase/articles/732225|powerbi-issue-the-as-connector-wont-install-or-i-cant-connect-to-data.md|g' *.md
